# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3b369de121f1115cf2a9fe5918250b388fa30e2a99edc2cbb243e7509afe7a779535f80fd8e56f5bda9920dd3c87d951d1139aa3e8bb3b47f157a50783e0f94

test:
  secret_key_base: fd8e8e840028159c3fa56040768d83510e116f1973ff1017b0f9c15484747768481d6ad69b4442948707c0bd489e145363986881eab9ef743a0a7f535b9ef83a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
